package com.phisit.wikicoutrylist.domain

data class CountryModel(
    val id: String,
    val countryName: String,
    val landMass: String
)

val fakeCountries = listOf(
    CountryModel("1", "Afghanistan", "Asia"),
    CountryModel("2", "Albania", "Europe"),
    CountryModel("3", "Algeria", "Africa"),
    CountryModel("4", "Andorra", "Europe"),
    CountryModel("5", "Angola", "Africa"),
    CountryModel("6", "Antigua and Barbuda", "North America"),
    CountryModel("7", "Argentina", "South America"),
    CountryModel("8", "Armenia", "Asia"),
    CountryModel("9", "Australia", "Oceania"),
    CountryModel("10", "Austria", "Europe"),
    CountryModel("11", "Azerbaijan", "Asia"),
    CountryModel("12", "Bahamas", "North America"),
    CountryModel("13", "Bahrain", "Asia"),
    CountryModel("14", "Bangladesh", "Asia"),
    CountryModel("15", "Barbados", "North America"),
    CountryModel("16", "Belarus", "Europe"),
    CountryModel("17", "Belgium", "Europe"),
    CountryModel("18", "Belize", "North America"),
    CountryModel("19", "Benin", "Africa"),
    CountryModel("20", "Bhutan", "Asia"),
    CountryModel("21", "Bolivia", "South America"),
    CountryModel("22", "Bosnia and Herzegovina", "Europe"),
    CountryModel("23", "Botswana", "Africa"),
    CountryModel("24", "Brazil", "South America"),
    CountryModel("25", "Brunei", "Asia"),
    CountryModel("26", "Bulgaria", "Europe"),
    CountryModel("27", "Burkina Faso", "Africa"),
    CountryModel("28", "Burundi", "Africa"),
    CountryModel("29", "Cabo Verde", "Africa"),
    CountryModel("30", "Cambodia", "Asia"),
    CountryModel("31", "Cameroon", "Africa"),
    CountryModel("32", "Canada", "North America"),
    CountryModel("33", "Central African Republic", "Africa"),
    CountryModel("34", "Chad", "Africa"),
    CountryModel("35", "Chile", "South America"),
    CountryModel("36", "China", "Asia"),
    CountryModel("37", "Colombia", "South America"),
    CountryModel("38", "Comoros", "Africa"),
    CountryModel("39", "Congo, Democratic Republic of the", "Africa"),
    CountryModel("40", "Congo, Republic of the", "Africa"),
    CountryModel("41", "Costa Rica", "North America"),
    CountryModel("42", "Croatia", "Europe"),
    CountryModel("43", "Cuba", "North America"),
    CountryModel("44", "Cyprus", "Asia"),
    CountryModel("45", "Czech Republic", "Europe"),
    CountryModel("46", "Denmark", "Europe"),
    CountryModel("47", "Djibouti", "Africa"),
    CountryModel("48", "Dominica", "North America"),
    CountryModel("49", "Dominican Republic", "North America"),
    CountryModel("50", "East Timor (Timor-Leste)", "Asia"),
    CountryModel("51", "Ecuador", "South America"),
    CountryModel("52", "Egypt", "Africa"),
    CountryModel("53", "El Salvador", "North America"),
    CountryModel("54", "Equatorial Guinea", "Africa"),
    CountryModel("55", "Eritrea", "Africa"),
    CountryModel("56", "Estonia", "Europe"),
    CountryModel("57", "Eswatini", "Africa"),
    CountryModel("58", "Ethiopia", "Africa"),
    CountryModel("59", "Fiji", "Oceania"),
    CountryModel("60", "Finland", "Europe"),
    CountryModel("61", "France", "Europe"),
    CountryModel("62", "Gabon", "Africa"),
    CountryModel("63", "Gambia", "Africa"),
    CountryModel("64", "Georgia", "Asia"),
    CountryModel("65", "Germany", "Europe"),
    CountryModel("66", "Ghana", "Africa"),
    CountryModel("67", "Greece", "Europe"),
    CountryModel("68", "Grenada", "North America"),
    CountryModel("69", "Guatemala", "North America"),
    CountryModel("70", "Guinea", "Africa"),
    CountryModel("71", "Guinea-Bissau", "Africa"),
    CountryModel("72", "Guyana", "South America"),
    CountryModel("73", "Haiti", "North America"),
    CountryModel("74", "Honduras", "North America"),
    CountryModel("75", "Hungary", "Europe"),
    CountryModel("76", "Iceland", "Europe"),
    CountryModel("77", "India", "Asia"),
    CountryModel("78", "Indonesia", "Asia"),
    CountryModel("79", "Iran", "Asia"),
    CountryModel("80", "Iraq", "Asia"),
    CountryModel("81", "Ireland", "Europe"),
    CountryModel("82", "Israel", "Asia"),
    CountryModel("83", "Italy", "Europe"),
    CountryModel("84", "Jamaica", "North America"),
    CountryModel("85", "Japan", "Asia"),
    CountryModel("86", "Jordan", "Asia"),
    CountryModel("87", "Kazakhstan", "Asia"),
    CountryModel("88", "Kenya", "Africa"),
    CountryModel("89", "Kiribati", "Oceania"),
    CountryModel("90", "Korea, North", "Asia"),
    CountryModel("91", "Korea, South", "Asia"),
    CountryModel("92", "Kosovo", "Europe"),
    CountryModel("93", "Kuwait", "Asia"),
    CountryModel("94", "Kyrgyzstan", "Asia"),
    CountryModel("95", "Laos", "Asia"),
    CountryModel("96", "Latvia", "Europe"),
    CountryModel("97", "Lebanon", "Asia"),
    CountryModel("98", "Lesotho", "Africa"),
    CountryModel("99", "Liberia", "Africa"),
    CountryModel("100", "Libya", "Africa"),
    CountryModel("101", "Liechtenstein", "Europe"),
    CountryModel("102", "Lithuania", "Europe"),
    CountryModel("103", "Luxembourg", "Europe"),
    CountryModel("104", "Madagascar", "Africa"),
    CountryModel("105", "Malawi", "Africa"),
    CountryModel("106", "Malaysia", "Asia"),
    CountryModel("107", "Maldives", "Asia"),
    CountryModel("108", "Mali", "Africa"),
    CountryModel("109", "Malta", "Europe"),
    CountryModel("110", "Marshall Islands", "Oceania"),
    CountryModel("111", "Mauritania", "Africa"),
    CountryModel("112", "Mauritius", "Africa"),
    CountryModel("113", "Mexico", "North America"),
    CountryModel("114", "Micronesia", "Oceania"),
    CountryModel("115", "Moldova", "Europe"),
    CountryModel("116", "Monaco", "Europe"),
    CountryModel("117", "Mongolia", "Asia"),
    CountryModel("118", "Montenegro", "Europe"),
    CountryModel("119", "Morocco", "Africa"),
    CountryModel("120", "Mozambique", "Africa"),
    CountryModel("121", "Myanmar", "Asia"),
    CountryModel("122", "Namibia", "Africa"),
    CountryModel("123", "Nauru", "Oceania"),
    CountryModel("124", "Nepal", "Asia"),
    CountryModel("125", "Netherlands", "Europe"),
    CountryModel("126", "New Zealand", "Oceania"),
    CountryModel("127", "Nicaragua", "North America"),
    CountryModel("128", "Niger", "Africa"),
    CountryModel("129", "Nigeria", "Africa"),
    CountryModel("130", "North Macedonia", "Europe"),
    CountryModel("131", "Norway", "Europe"),
    CountryModel("132", "Oman", "Asia"),
    CountryModel("133", "Pakistan", "Asia"),
    CountryModel("134", "Palau", "Oceania"),
    CountryModel("135", "Palestine", "Asia"),
    CountryModel("136", "Panama", "North America"),
    CountryModel("137", "Papua New Guinea", "Oceania"),
    CountryModel("138", "Paraguay", "South America"),
    CountryModel("139", "Peru", "South America"),
    CountryModel("140", "Philippines", "Asia"),
    CountryModel("141", "Poland", "Europe"),
    CountryModel("142", "Portugal", "Europe"),
    CountryModel("143", "Qatar", "Asia"),
    CountryModel("144", "Romania", "Europe"),
    CountryModel("145", "Russia", "Europe"),
    CountryModel("146", "Rwanda", "Africa"),
    CountryModel("147", "Saint Kitts and Nevis", "North America"),
    CountryModel("148", "Saint Lucia", "North America"),
    CountryModel("149", "Saint Vincent and the Grenadines", "North America"),
    CountryModel("150", "Samoa", "Oceania"),
    CountryModel("151", "San Marino", "Europe"),
    CountryModel("152", "Sao Tome and Principe", "Africa"),
    CountryModel("153", "Saudi Arabia", "Asia"),
    CountryModel("154", "Senegal", "Africa"),
    CountryModel("155", "Serbia", "Europe"),
    CountryModel("156", "Seychelles", "Africa"),
    CountryModel("157", "Sierra Leone", "Africa"),
    CountryModel("158", "Singapore", "Asia"),
    CountryModel("159", "Slovakia", "Europe"),
    CountryModel("160", "Slovenia", "Europe"),
    CountryModel("161", "Solomon Islands", "Oceania"),
    CountryModel("162", "Somalia", "Africa"),
    CountryModel("163", "South Africa", "Africa"),
    CountryModel("164", "South Sudan", "Africa"),
    CountryModel("165", "Spain", "Europe"),
    CountryModel("166", "Sri Lanka", "Asia"),
    CountryModel("167", "Sudan", "Africa"),
    CountryModel("168", "Suriname", "South America"),
    CountryModel("169", "Sweden", "Europe"),
    CountryModel("170", "Switzerland", "Europe"),
    CountryModel("171", "Syria", "Asia"),
    CountryModel("172", "Taiwan", "Asia"),
    CountryModel("173", "Tajikistan", "Asia"),
    CountryModel("174", "Tanzania", "Africa"),
    CountryModel("175", "Thailand", "Asia"),
    CountryModel("176", "Togo", "Africa"),
    CountryModel("177", "Tonga", "Oceania"),
    CountryModel("178", "Trinidad and Tobago", "North America"),
    CountryModel("179", "Tunisia", "Africa"),
    CountryModel("180", "Turkey", "Asia"),
    CountryModel("181", "Turkmenistan", "Asia"),
    CountryModel("182", "Tuvalu", "Oceania"),
    CountryModel("183", "Uganda", "Africa"),
    CountryModel("184", "Ukraine", "Europe"),
    CountryModel("185", "United Arab Emirates", "Asia"),
    CountryModel("186", "United Kingdom", "Europe"),
    CountryModel("187", "United States", "North America"),
    CountryModel("188", "Uruguay", "South America"),
    CountryModel("189", "Uzbekistan", "Asia"),
    CountryModel("190", "Vanuatu", "Oceania"),
    CountryModel("191", "Vatican City", "Europe"),
    CountryModel("192", "Venezuela", "South America"),
    CountryModel("193", "Vietnam", "Asia"),
    CountryModel("194", "Yemen", "Asia"),
    CountryModel("195", "Zambia", "Africa"),
    CountryModel("196", "Zimbabwe", "Africa")
)